### ISSUE TITLE
Can't manage completion to work

### ISSUE THREAD

**Issue by LyGeorge** [jdrupal-dev/css-vars.nvim#1]
Hello, i set up all according to readme, but unfortunately for some reason completion doesn't work. If you have some time could you pls help me with it?

**Comment by jdrupal-dev** [comment]
Are you by any chance using Windows? I did not build this plugin to support Windows (yet).

**Comment by LyGeorge** [comment]
> Are you by any chance using Windows? I did not build this plugin to support Windows (yet).

I use MacOS

**Comment by jdrupal-dev** [comment]
And you have ripgrep installed?
Can you also include the output of the tmp file that starts with `/tmp/css-vars`?

**Comment by LyGeorge** [comment]
I've just looked into my file and i have that variable in it, but i have no completion for it

**Comment by jdrupal-dev** [comment]
So if you type the following, you do not see any suggestions?
```
body {
  background: var(--[CURSOR HERE])
}
```
What is the name/extension of the file you are editing?

**Comment by LyGeorge** [comment]
<img width="1167" alt="Screenshot 2024-03-29 at 15 37 10" src="https://github.com/jdrupal-dev/css-vars.nvim/assets/116944025/2349d43e-3361-4adc-b631-a356f48ae4c8">

**Comment by LyGeorge** [comment]
<img width="853" alt="Screenshot 2024-03-29 at 15 37 47" src="https://github.com/jdrupal-dev/css-vars.nvim/assets/116944025/5b55bf1f-6fb1-485d-9655-6a57dbc44b52">

**Comment by LyGeorge** [comment]
May be something wrong my cmp config.

**Comment by jdrupal-dev** [comment]
I just experimented with having it as a custom cmp source instead of snippets.
Try adding it as a dependency to nvim-cmp, and configure it to use the source, like this:
```
  "hrsh7th/nvim-cmp",
  dependencies = {
    -- other deps
    {
      "jdrupal-dev/css-vars.nvim",
      branch = "cmp-source", -- Important to use this branch.
      opts = {},
    },
  },
  config = function()
     cmp.setup({
      -- Sources for autocompletion.
      sources = cmp.config.sources({
        { name = "nvim_lsp" },
        { name = "css_vars" },
        -- other sources...
      }),
    })
    -- more configuration...
  end
```

Please let me know how that works.

PS: The new branch requires plenary to be installed.

**Comment by LyGeorge** [comment]
@jdrupal-dev now it works! Thank you a lot!

**Comment by jdrupal-dev** [comment]
Cool, will close this once I have updated the readme and merged to master.
