### ISSUE TITLE
Styled Components / CSS-in-JS

### ISSUE THREAD

**Issue by cosmic-bytes** [jdrupal-dev/css-vars.nvim#3]
Thank you so much for your work on this plugin! When I try to use it in a ".ts" file for styled components it is not allowing for autocompletion - due to lines 50-52 hardcoding css, sass, etc file types. Is there any way we could expose to the user which file types they want (via options) to include for config? or add typescript/js files for users using CSS-in-JS? I personally hate to force that behavior to all users if they do not need it... Thanks!

**Comment by cosmic-bytes** [comment]
I have a branch going with this feature for you to look over - just not able to push to your repo

**Comment by jdrupal-dev** [comment]
Hi @JoshDPT.
I think it is a good thing to be able to configure the filetypes.
You should be able to fork the repo and make a PR from that 😀

**Comment by cosmic-bytes** [comment]
Awesome I will fork it and let you look at it! First time with Lua so I will def need you to look over and test (if possible)! Thanks again @jdrupal-dev!

**Comment by jdrupal-dev** [comment]
@JoshDPT Thank you for providing a PR. I made a few changes and opened a new PR: https://github.com/jdrupal-dev/css-vars.nvim/pull/5

Please take a look and let me know what you think 🙂
